apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi-web
  name: multi-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-web
  strategy: {}
  template:
    metadata:
      labels:
        app: multi-web
    spec:
      containers:
      - image: swithan/ctf_challenges:multi-web
        name: webapp
        imagePullPolicy: Always
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: regcred
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: multi-web
  labels:
    run: multi-web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: multi-web
  type: LoadBalancer