apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat-the-boss
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beat-the-boss
  template:
    metadata:
      labels:
        app: beat-the-boss
    spec:
      containers:
      - name: beat-the-boss
        image: swithan/ctf_challenges:beat_the_boss
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "1"
          limits:
            memory: "128Mi"
            cpu: "2.5"
        ports:
        - containerPort: 9991
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: beat-the-boss
  labels:
    run: beat-the-boss
spec:
  ports:
  - port: 9991
    protocol: TCP
  selector:
    app: beat-the-boss
  type: LoadBalancer