apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-best
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-best
  template:
    metadata:
      labels:
        app: data-best
    spec:
      containers:
      - name: data-best
        image: swithan/ctf_challenges:data_best
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "0.1"
          limits:
            memory: "64Mi"
            cpu: "0.3"
        ports:
        - containerPort: 8888
          protocol: TCP
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: data-best
  labels:
    run: data-best
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: data-best
  type: NodePort