apiVersion: apps/v1
kind: Deployment
metadata:
  name: family-member
spec:
  replicas: 1
  selector:
    matchLabels:
      run: family-member
  template:
    metadata:
      labels:
        run: family-member
    spec:
      containers:
      - name: family-member
        image: swithan/ctf_challenges:family_member
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
            protocol: TCP
        env:
        - name: POSTGRES_DB
          valueFrom: 
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.5"
          limits:
            memory: "512Mi"
            cpu: "0.8"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: family-member
  labels: 
    run: family-member
spec:
  type: LoadBalancer
  selector:
    run: family-member
  ports:
  - port: 5432
  