apiVersion: apps/v1
kind: Deployment
metadata:
  name: family-member
spec:
  replicas: 2
  selector:
    matchLabels:
      run: family-member
  template:
    metadata:
      labels:
        run: family-member
    spec:
      containers:
      - name: family-member
        image: swithan/ctf_challenges:db_murphy
        ports:
          - containerPort: 5432
            protocol: TCP
        env:
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "32Mi"
            cpu: "0.01"
          limits:
            memory: "64Mi"
            cpu: "0.03"
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: family-member
  labels: 
    run: family-member
spec:
  type: LoadBalancer
  selector:
    run: family-member
  ports:
  - port: 5432
  