apiVersion: apps/v1
kind: Deployment
metadata:
  name: flute
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flute
  template:
    metadata:
      labels:
        app: flute
    spec:
      containers:
      - image: swithan/ctf_challenges:flute_alors
        name: flute
        imagePullPolicy: Always
        resources: 
          requests: 
            memory: "16Mi"
            cpu: "0.01"
          limits:
            memory: "32Mi"
            cpu: "0.1"
        ports:
        - containerPort: 80 
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: flute
  labels:
    run: flute
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: flute
  type: LoadBalancer