apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
  labels:
    app: frontend-depl
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: no-time-front
          image: swithan/ctf_challenges:no_time_front
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels: 
    app: frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
