apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flute
  name: flute
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flute
  strategy: {}
  template:
    metadata:
      labels:
        app: flute
    spec:
      containers:
      - image: swithan/ctf_challenges:flutest
        name: webapp
        imagePullPolicy: Always
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 4040 
      imagePullSecrets:
      - name: regcred
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: flute
  labels:
    run: flute
spec:
  ports:
  - port: 4040
    protocol: TCP
  selector:
    app: flute
  type: LoadBalancer