apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ctf-api
  name: ctf-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ctf-api
  strategy: {}
  template:
    metadata:
      labels:
        app: ctf-api
    spec:
      containers:
      - image: swithan/ctf_challenges:ctf_api
        name: webapp
        imagePullPolicy: Always
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000 
      imagePullSecrets:
      - name: regcred
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: ctf-api
  labels:
    run: ctf-api
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: ctf-api
  type: LoadBalancer