apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: no-time
  name: no-time
spec:
  replicas: 3
  selector:
    matchLabels:
      app: no-time
  strategy: {}
  template:
    metadata:
      labels:
        app: no-time
    spec:
      containers:
      - image: swithan/ctf_challenges:no_time_full
        name: webapp
        imagePullPolicy: Always
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3080 
      imagePullSecrets:
      - name: regcred
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: no-time
  labels:
    run: no-time
spec:
  ports:
  - port: 3080
    protocol: TCP
  selector:
    app: no-time
  type: LoadBalancer