apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: no-time
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: no-time
        tier: backend
        track: stable
    spec:
      containers:
        - name: no-time-back
          image: swithan/ctf_challenges:no_time_back
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend-svc
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: http
---